import {existsSync,readFileSync,writeFileSync,mkdirSync,readdirSync,openSync,closeSync,unlinkSync,renameSync,cpSync,statSync,readSync,lstatSync} from 'node:fs';
import {resolve,join,dirname,isAbsolute,relative} from 'node:path';
import {homedir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {createHash,randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
export const ROOT=fileURLToPath(new URL('../',import.meta.url));
export const HOME=resolve(process.env.QINGHUA_SKILLS_HOME||join(homedir(),'.qinghua-skills'));
export const SKILL_DIR=join(HOME,'skills','card-video','2.1.0');
export const VERSION='0.1.0';
export const alive=pid=>{if(!Number.isSafeInteger(pid)||pid<1)return false;try{process.kill(pid,0);return true;}catch(e){return e.code==='EPERM';}};
export function atomicJson(path,value){mkdirSync(dirname(path),{recursive:true});const tmp=path+'.'+randomUUID()+'.tmp';writeFileSync(tmp,JSON.stringify(value,null,2)+'\n',{mode:0o600});renameSync(tmp,path);}
export function readJson(path){return JSON.parse(readFileSync(path,'utf8'));}
export function platformKey(platform=process.platform,arch=process.arch){const supported=new Set(['darwin-arm64','darwin-x64','win32-x64','linux-x64','linux-arm64']);const key=platform+'-'+arch;if(!supported.has(key))throw new Error('暂不支持此平台：'+key);return key;}
async function killTree(child){
 if(!child.pid)return;
 if(process.platform==='win32')await new Promise((done,reject)=>{
  const killer=spawn(join(process.env.SystemRoot||'C:\\Windows','System32','taskkill.exe'),['/PID',String(child.pid),'/T','/F'],{shell:false,windowsHide:true,stdio:'ignore'});
  const timer=setTimeout(()=>{killer.kill();const e=new Error('无法确认任务进程树已清理，需要人工检查后再操作');e.cleanupRequired=true;reject(e);},10000);
  killer.on('error',e=>{clearTimeout(timer);e.cleanupRequired=true;reject(e);});
  killer.on('close',code=>{clearTimeout(timer);if(code===0||code===128)done();else{const e=new Error('任务进程树清理失败');e.cleanupRequired=true;reject(e);}});
 });else{
  try{process.kill(-child.pid,'SIGTERM');}catch(e){if(e.code!=='ESRCH')throw e;}
  await new Promise(r=>setTimeout(r,1000));
  try{process.kill(-child.pid,'SIGKILL');}catch(e){if(e.code!=='ESRCH'){e.cleanupRequired=true;throw e;}}
 }
}
export function command(cmd,args,options={}){return new Promise((done,reject)=>{
 const child=spawn(cmd,args,{shell:false,detached:process.platform!=='win32',windowsHide:true,cwd:options.cwd,env:options.env||process.env,stdio:options.log?['ignore','inherit','inherit']:['ignore','pipe','pipe']});let out='',err='',finished=false,timedOut=false;
 const finish=(error,result)=>{if(finished)return;finished=true;clearTimeout(timer);error?reject(error):done(result);};
 const timer=setTimeout(async()=>{timedOut=true;try{await killTree(child);finish(new Error('命令超时，已终止任务进程树；请查看日志后重试。'));}catch(e){e.cleanupRequired=true;finish(e);}},options.timeout||30000);
 if(!options.log){child.stdout.on('data',x=>{out=(out+x).slice(-200000);});child.stderr.on('data',x=>{err=(err+x).slice(-200000);});}
 child.on('error',e=>finish(e));child.on('close',code=>{if(timedOut)return;const result={code,stdout:out,stderr:err};if(code!==0&&!options.allowFailure)finish(new Error('执行失败（'+code+'）：'+redact(err||out).slice(-2000)));else finish(null,result);});
});}
export function redact(s){return String(s).replace(/((?:api[_-]?key|token|secret|password)\s*[=:]\s*)[^\s,;]+/gi,'$1[已隐藏]').replace(/Bearer\s+[A-Za-z0-9._-]+/g,'Bearer [已隐藏]');}
export async function findPython(){const candidates=[];const managed=join(HOME,'runtime','python',platformKey(),'python',process.platform==='win32'?'python.exe':'bin/python3');candidates.push(managed);const versions=join(homedir(),'.workbuddy','binaries','python','versions');if(process.env.QINGHUA_FORCE_MANAGED_PYTHON!=='1'&&existsSync(versions))for(const v of readdirSync(versions).sort().reverse())candidates.push(join(versions,v,process.platform==='win32'?'python.exe':'bin/python3'));for(const path of candidates){if(!existsSync(path))continue;try{const r=await command(path,['-c','import sys,venv,ensurepip,ssl,json; assert sys.version_info>=(3,10); print(json.dumps({"path":sys.executable,"version":list(sys.version_info[:3])}))'],{timeout:4000});const result=JSON.parse(r.stdout.trim());return result;}catch{}}return null;}
export function catalog(){return {ok:true,connectorVersion:VERSION,platform:process.platform,arch:process.arch,skills:[{id:'card-video',name:'卡片视频-学员版',version:'2.1.0',installed:existsSync(join(SKILL_DIR,'package.json')),skillDir:SKILL_DIR,capabilities:['中文卡片动画视频','环境诊断','初始化与修复','无费用安装测试片','免费在线配音'],validation:'Mac Apple Silicon 已实测；Windows x64、Intel Mac 与 Linux 尚待实机验收',notes:'通过本连接器使用，不声称自动注册到 WorkBuddy 独立技能市场。'}]};}
export function deploy({restore=false}={}){platformKey();const directoryExists=existsSync(SKILL_DIR);if(directoryExists&&!lstatSync(SKILL_DIR).isDirectory())throw new Error('技能目录被非目录文件占用');const installed=existsSync(join(SKILL_DIR,'package.json'));if(installed&&!restore)return SKILL_DIR;const payload=join(ROOT,'payload','card-video');const manifest=readJson(join(ROOT,'payload-manifest.json'));const stage=directoryExists?SKILL_DIR:SKILL_DIR+'.stage-'+randomUUID();for(const [name,hash] of Object.entries(manifest)){const file=resolve(payload,name);if(relative(payload,file).startsWith('..')||!lstatSync(file).isFile())throw new Error('包路径越界或包含非普通文件');if(createHash('sha256').update(readFileSync(file)).digest('hex')!==hash)throw new Error('技能包完整性校验失败：'+name);const target=join(stage,name);mkdirSync(dirname(target),{recursive:true});if(existsSync(target)&&!lstatSync(target).isFile())throw new Error('安装目录存在非普通文件：'+name);cpSync(file,target,{dereference:false});}if(!directoryExists)renameSync(stage,SKILL_DIR);return SKILL_DIR;}
export function runtimeEnv(python){return {...process.env,CARD_BASE_PYTHON:python,PYTHONUTF8:'1',PATH:dirname(process.execPath)+(process.platform==='win32'?';':':')+(process.env.PATH||'')};}
export async function doctor(){platformKey();const python=await findPython();if(!existsSync(join(SKILL_DIR,'package.json')))return {ok:false,installed:false,python,skillDir:SKILL_DIR,nextAction:'initialize_skill'};const integrity={name:'技能文件完整性',ok:true,detail:'固定版本 2.1.0 完整'};try{for(const [name,hash] of Object.entries(readJson(join(ROOT,'payload-manifest.json')))){const file=join(SKILL_DIR,name);if(!existsSync(file)||!lstatSync(file).isFile()||createHash('sha256').update(readFileSync(file)).digest('hex')!==hash)throw new Error('文件缺失或被修改：'+name);}}catch(e){Object.assign(integrity,{ok:false,error:e.message,nextAction:'repair_skill'});}const r=await command(process.execPath,[join(SKILL_DIR,'scripts','setup.mjs'),'--check','--json'],{cwd:SKILL_DIR,env:runtimeEnv(python?.path||''),timeout:20000,allowFailure:true});try{const report=JSON.parse(r.stdout);return {...report,ok:report.ok&&integrity.ok,checks:[...report.checks,integrity],installed:true,basePython:python,skillDir:SKILL_DIR};}catch{throw new Error('诊断结果不可解析：'+redact(r.stderr).slice(-1000));}}
export function jobFile(id){if(!/^[0-9a-f-]{36}$/.test(id))throw new Error('无效任务编号');return join(HOME,'tasks',id+'.json');}
export function readJob(id){const f=jobFile(id);if(!existsSync(f))throw new Error('任务不存在');const job=readJson(f);if(['running','queued'].includes(job.state)&&job.pid&&!alive(job.pid)){job.state='interrupted';job.error='后台任务已退出，任务未完成；请重新初始化或修复。';}const log=join(HOME,'tasks',id+'.log');if(existsSync(log)){const fd=openSync(log,'r');const size=statSync(log).size;const buffer=Buffer.alloc(Math.min(size,6000));try{readSync(fd,buffer,0,buffer.length,size-buffer.length);job.logTail=redact(buffer.toString()).split(/\r?\n/).slice(-35).join('\n');}finally{closeSync(fd);}}return job;}
export function listJobs(){const dir=join(HOME,'tasks');if(!existsSync(dir))return {ok:true,jobs:[]};return {ok:true,jobs:readdirSync(dir).filter(x=>x.endsWith('.json')).map(x=>readJob(x.slice(0,-5))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,10)};}
export function beginJob(action,params={}){platformKey();if(!['initialize','repair','smoke','render'].includes(action))throw new Error('不支持的操作');mkdirSync(join(HOME,'tasks'),{recursive:true});const lock=join(HOME,'active-job.json');if(existsSync(lock)){const old=readJson(lock);const oldJob=readJob(old.id);if(oldJob.state==='cleanup_required')throw new Error('上一任务进程树未确认清理，请核对任务日志并处理后再启动。');const active=alive(oldJob.pid)||(['queued','running'].includes(oldJob.state)&&Date.now()-Date.parse(oldJob.createdAt)<60000);if(active)return {ok:false,busy:true,jobId:old.id,message:'已有环境或视频任务正在执行，请查询该任务。'};unlinkSync(lock);}const id=randomUUID();let fd;try{fd=openSync(lock,'wx',0o600);writeFileSync(fd,JSON.stringify({id}));}catch{throw new Error('已有任务启动，请稍后查询。');}finally{if(fd!==undefined)closeSync(fd);}const job={id,action,params,state:'queued',phase:'等待启动',createdAt:new Date().toISOString()};atomicJson(jobFile(id),job);const logFd=openSync(join(HOME,'tasks',id+'.log'),'a',0o600);try{const child=spawn(process.execPath,[join(ROOT,'dist','worker.mjs'),id],{env:process.env,detached:true,windowsHide:true,stdio:['ignore',logFd,logFd]});child.on('error',e=>{atomicJson(jobFile(id),{...job,state:'failed',error:redact(e.message)});if(existsSync(lock)&&readJson(lock).id===id)unlinkSync(lock);});child.unref();}finally{closeSync(logFd);}return {ok:true,jobId:id,state:'queued',message:'任务已启动，请调用 get_task_status 查看进度；未完成前不要称环境已安装。'};}
export function guide(){return {ok:true,skillDir:SKILL_DIR,registeredInWorkBuddy:false,guide:'先 check_environment，缺失则 initialize_skill；得到 jobId 后用 get_task_status 查询到 completed，再检查环境。修复用 repair_skill，测试用 create_test_video。文案已确定时 render_card_video 可使用免费在线配音生成视频；所有文件存放在本机，不上传。Windows x64/Intel Mac/Linux 为待实机验收平台。',scriptExample:readJson(join(ROOT,'payload/card-video/examples/demo-script.json'))};}
