import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';
import {z} from 'zod';
import {VERSION,catalog,doctor,beginJob,readJob,listJobs,guide,redact} from './runtime.mjs';
const server=new McpServer({name:'qinghua-workbuddy-skill-kit',version:VERSION});
const answer=output=>({content:[{type:'text',text:JSON.stringify(output,null,2)}],structuredContent:output});
const tool=(name,description,schema,handler,readOnly=false)=>server.registerTool(name,{description,inputSchema:schema,annotations:{readOnlyHint:readOnly,destructiveHint:false,idempotentHint:readOnly,openWorldHint:!readOnly}},async args=>{try{return answer(await handler(args));}catch(e){return {isError:true,content:[{type:'text',text:redact(e.message)}]};}});
tool('list_skills','列出本连接器已支持的技能与本机部署状态；首版仅卡片视频学员版。',{},catalog,true);
tool('check_environment','只读检查卡片视频依赖环境，不下载、不安装；未安装时返回 initialize_skill 提示。',{},doctor,true);
tool('initialize_skill','在本机独立目录安装固定版本的卡片视频环境。需要下载安装组件，返回 jobId；必须查询到 completed 才算成功。',{},()=>beginJob('initialize'));
tool('repair_skill','恢复固定版本的技能代码、字体与环境依赖，保留已有视频与本机凭据。只在确认旧进程已退出时清除遗留安装锁；返回 jobId。',{},()=>beginJob('repair'));
tool('create_test_video','生成十秒中文动画与测试音轨，不调用付费API。请先确认环境已通过，返回 jobId。',{},()=>beginJob('smoke'));
tool('get_task_status','查询后台安装或视频任务的真实状态、日志尾部和成片路径。queued/running 不能视为已完成。',{jobId:z.string().uuid()},({jobId})=>readJob(jobId),true);
tool('list_tasks','查询最近十个本机任务，重启 WorkBuddy 后也可查看已启动任务。',{},listJobs,true);
tool('get_skill_guide','查看本连接器使用方法、技能实际目录和卡片视频文案JSON示例。',{},guide,true);
const line=z.object({text:z.string().max(150),style:z.enum(['title','body','emphasis']).optional()});
const slide=z.object({lines:z.array(line).min(1).max(8),narration:z.string().min(1).max(1000),duration:z.number().positive().max(120).optional()});
tool('render_card_video','将已确定的文案制作成中文卡片动画视频，使用免费在线配音；配音文本会发送给在线配音服务，视频文件保存在本机。请先检查环境。返回 jobId，需等待真实完成。',{script:z.object({slides:z.array(slide).min(1).max(30)}),landscape:z.boolean().default(false)},args=>beginJob('render',args));
if(process.argv.includes('--version'))console.log(VERSION);else await server.connect(new StdioServerTransport());
