import {existsSync,readFileSync,writeFileSync,mkdirSync,unlinkSync} from 'node:fs';
import {join,dirname} from 'node:path';
import {HOME,SKILL_DIR,readJson,atomicJson,jobFile,deploy,runtimeEnv,command,alive,redact} from './runtime.mjs';
import {ensurePython} from './python.mjs';
const id=process.argv[2];const file=jobFile(id);let job=readJson(file);
const phase=text=>{job={...job,phase:text,updatedAt:new Date().toISOString()};atomicJson(file,job);console.log(text);};
function staleSkillLock(){const path=join(SKILL_DIR,'.runtime','setup.lock');if(!existsSync(path))return;const pid=Number(readFileSync(path,'utf8').trim());if(!Number.isSafeInteger(pid)||pid<1)throw new Error('安装锁格式异常，无法安全自动清除；请核对安装任务。');if(alive(pid))throw new Error('已有安装进程运行（PID '+pid+'），不会清除其锁。');unlinkSync(path);console.log('已核对旧安装进程不在运行，清除遗留锁。');}
try{job={...job,state:'running',pid:process.pid};atomicJson(file,job);phase('校验并部署学员技能包');if(job.action==='repair')staleSkillLock();deploy({restore:job.action==='repair'});const python=await ensurePython(phase);const env=runtimeEnv(python);let result;
 if(['initialize','repair'].includes(job.action)){if(job.action==='repair')staleSkillLock();phase(job.action==='repair'?'修复锁定的环境依赖':'安装锁定的环境依赖');await command(python,[join(SKILL_DIR,'scripts','bootstrap.py'),'setup','--json',...(job.action==='repair'?['--repair']:[])],{cwd:SKILL_DIR,env,log:true,timeout:2400000});phase('复验环境');const r=await command(process.execPath,[join(SKILL_DIR,'scripts','setup.mjs'),'--check','--json'],{cwd:SKILL_DIR,env,timeout:30000});result=JSON.parse(r.stdout);if(!result.ok)throw new Error('安装后环境复验未通过');}
 else{const dir=join(HOME,'outputs',id);mkdirSync(dir,{recursive:true});const args=[join(SKILL_DIR,'scripts','bootstrap.py')];if(job.action==='smoke'){phase('生成十秒无费用测试片');args.push('smoke','--project',dir);}else if(job.action==='render'){phase('使用免费在线配音制作卡片视频');const script=join(dir,'script.json');writeFileSync(script,JSON.stringify(job.params.script,null,2));args.push('run',script,'--project',dir,'--tts','edge');if(job.params.landscape)args.push('--landscape');}else throw new Error('未知任务');await command(python,args,{cwd:SKILL_DIR,env,log:true,timeout:2400000});result={ok:true,path:join(dir,'output.mp4'),kind:job.action,paidApiUsed:false};if(job.action==='smoke')Object.assign(result,readJson(join(dir,'验收结果.json')));}
 job={...job,state:'completed',phase:'已完成',result,finishedAt:new Date().toISOString()};atomicJson(file,job);
}catch(e){job={...job,state:e.cleanupRequired?'cleanup_required':'failed',phase:'执行失败',error:redact(e.message),finishedAt:new Date().toISOString()};atomicJson(file,job);console.error(job.error);process.exitCode=1;}finally{const lock=join(HOME,'active-job.json');if(job.state!=='cleanup_required'&&existsSync(lock)&&readJson(lock).id===id)unlinkSync(lock);}
